name: base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:

    - name: Print Hello World
      run: echo "Hello World!"